src/Domain/Appointment/Entity/Appointment.php
<?php

namespace App\Domain\Appointment\Entity;

use App\Domain\Appointment\Repository\AppointmentRepository;
use App\Domain\Auth\Entity\User;
use App\Domain\Payment\Entity\Payment;
use App\Domain\Prestation\Entity\Prestation;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity( repositoryClass: AppointmentRepository::class )]
class Appointment
{
    public const STATUS_PENDING = 'pending';
    public const STATUS_CONFIRMED = 'confirmed';
    public const STATUS_CANCELED = 'canceled';
    public const STATUS_END = 'end';

    public static array $statusList = [
        self::STATUS_PENDING,
        self::STATUS_CONFIRMED,
        self::STATUS_CANCELED,
    ];

    public const PAYMENT_STATUS_SUCCESS = 'success';
    public const PAYMENT_STATUS_PENDING = 'pending';
    public const PAYMENT_STATUS_FAILED = 'failed';

    public function isStatusPending() : bool
    {
        return $this->getStatus() === self::STATUS_PENDING;
    }

    public function isStatusConfirmed() : bool
    {
        return $this->getStatus() === self::STATUS_CONFIRMED;
    }

    public function isStatusCanceled() : bool
    {
        return $this->getStatus() === self::STATUS_CANCELED;
    }

    public static array $paymentStatusList = [
        self::PAYMENT_STATUS_SUCCESS,
        self::PAYMENT_STATUS_PENDING,
        self::PAYMENT_STATUS_FAILED,
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne( inversedBy: 'appointments' )]
    #[ORM\JoinColumn( nullable: false )]
    private ?User $client = null;

    #[ORM\ManyToOne( inversedBy: 'appointments' )]
    #[ORM\JoinColumn( nullable: false )]
    private ?Prestation $prestation = null;

    #[ORM\Column( type: Types::DATE_MUTABLE )]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column( type: Types::TIME_MUTABLE )]
    private ?\DateTimeInterface $time = null;

    #[ORM\Column( type: Types::STRING, length: 50 )]
    private string $status = self::STATUS_PENDING;

    #[ORM\Column( type: "decimal", precision: 10, scale: 2, nullable: true )]
    private ?float $amount = null;

    #[ORM\Column( type: Types::STRING, length: 50, nullable: true )]
    private ?string $paymentStatus = self::PAYMENT_STATUS_PENDING;

    #[ORM\OneToMany( mappedBy: 'appointment', targetEntity: Payment::class, orphanRemoval: true )]
    private Collection $payments;

    #[ORM\Column( type: Types::STRING, length: 50, nullable: true )]
    private ?string $token = null;

    public function __construct()
    {
        $this->payments = new ArrayCollection();
    }

    public function getId() : ?int
    {
        return $this->id;
    }

    public function getClient() : ?User
    {
        return $this->client;
    }

    public function setClient( ?User $client ) : self
    {
        $this->client = $client;

        return $this;
    }

    public function getPrestation() : ?Prestation
    {
        return $this->prestation;
    }

    public function setPrestation( ?Prestation $prestation ) : self
    {
        $this->prestation = $prestation;

        return $this;
    }

    public function getDate() : ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate( ?\DateTimeInterface $date ) : self
    {
        $this->date = $date;

        return $this;
    }

    public function getTime() : ?\DateTimeInterface
    {
        return $this->time;
    }

    public function setTime( \DateTimeInterface $time ) : self
    {
        $this->time = $time;

        return $this;
    }

    public function getStatus() : string
    {
        return $this->status;
    }

    public function setStatus( string $status ) : self
    {
        if ( !in_array( $status, self::$statusList, true ) ) {
            throw new \InvalidArgumentException( 'Le statut n\'est pas valide.' );
        }

        $this->status = $status;

        return $this;
    }

    public function setIsConfirmed( bool $value ) : self
    {
        $this->setStatus( $value ? self::STATUS_CONFIRMED : self::STATUS_CANCELED );

        return $this;
    }

    public function isPassed() : bool
    {

        $isAppointmentDatePassed = $this->getDate()->format( 'Y-m-d' ) < ( new \DateTime() )->format( 'Y-m-d' );

        if ( $isAppointmentDatePassed ) {
            return true;
        }

        if ( $this->getDate()->format( 'Y-m-d' ) === ( new \DateTime() )->format( 'Y-m-d' ) ) {
            return $this->getTime()->format( 'H:i' ) <= ( new \DateTime() )->format( 'H:i' );
        }

        return false;
    }

    public function getAmount() : ?float
    {
        return $this->amount;
    }

    public function setAmount( ?float $amount ) : static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getPaymentStatus() : ?string
    {
        return $this->paymentStatus;
    }

    public function setPaymentStatus( ?string $paymentStatus ) : static
    {
        $this->paymentStatus = $paymentStatus;

        return $this;
    }

    public function isPaid() : bool
    {
        return $this->getPaymentStatus() === self::PAYMENT_STATUS_SUCCESS;
    }

    /**
     * @return Collection<int, Payment>
     */
    public function getPayments() : Collection
    {
        return $this->payments;
    }

    public function addPayment( Payment $payment ) : static
    {
        if ( !$this->payments->contains( $payment ) ) {
            $this->payments->add( $payment );
            $payment->setAppointment( $this );
        }

        return $this;
    }

    public function removePayment( Payment $payment ) : static
    {
        if ( $this->payments->removeElement( $payment ) ) {
            // set the owning side to null (unless already changed)
            if ( $payment->getAppointment() === $this ) {
                $payment->setAppointment( null );
            }
        }

        return $this;
    }

    public function getToken() : ?string
    {
        return $this->token;
    }

    public function setToken( ?string $token ) : static
    {
        $this->token = $token;

        return $this;
    }
}

src/Domain/Appointment/Form/AppointmentManageUpdateForm.php
<?php

namespace App\Domain\Appointment\Form;

use App\Domain\Appointment\Dto\AppointmentManageUpdateData;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AppointmentManageUpdateForm extends AbstractType
{
    public function buildForm( FormBuilderInterface $builder, array $options ) : void
    {
        $builder
            ->add( 'date', DateType::class, [
                'label' => 'Date du rendez-vous',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-input-md flatpickr-date-input appointment-date-choice'
                ],
                'label_attr' => [
                    'class' => 'label'
                ],
            ] )
            ->add( 'time', TimeType::class, [
                'label' => 'Heure du rendez-vous',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-input-md flatpickr-time-input'
                ],
                'label_attr' => [
                    'class' => 'label'
                ],
            ] );
    }

    public function configureOptions( OptionsResolver $resolver ) : void
    {
        $resolver->setDefaults( [
            'data_class' => AppointmentManageUpdateData::class,
        ] );
    }
}

src/Http/Admin/Controller/AppointmentController.php
<?php

namespace App\Http\Admin\Controller;

use App\Domain\Appointment\Dto\AppointmentData;
use App\Domain\Appointment\Entity\Appointment;
use App\Domain\Appointment\Form\NewAppointmentForm;
use App\Domain\Appointment\Service\AppointmentService;
use App\Http\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted( 'ROLE_ADMIN' )]
#[Route( '/rendez-vous', name: 'appointment_' )]
class AppointmentController extends AbstractController
{
    public function __construct( private readonly AppointmentService $appointmentService )
    {
    }

    #[Route( '/', name: 'index' )]
    public function index() : Response
    {
        $appointments = $this->appointmentService->getAppointments();
        $appointmentsToday = [];
        foreach ( $appointments as $appointment ) {
            if ( $appointment->getDate()->format( 'Y-m-d' ) === date( 'Y-m-d' ) ) {
                $appointmentsToday[] = $appointment;
            }
        }

        // group appointments by date and order by date
        $appointmentsByDate = [];
        foreach ( $appointments as $appointment ) {
            $date = $appointment->getDate()->format( 'Y-m-d' );
            if ( !isset( $appointmentsByDate[$date] ) ) {
                $appointmentsByDate[$date] = [];
            }
            $appointmentsByDate[$date][] = $appointment;
        }
        ksort( $appointmentsByDate );

        // Separate after today and before today
        $appointmentsAfterToday = [];
        $appointmentsBeforeToday = [];
        foreach ( $appointmentsByDate as $date => $appointments ) {
            if ( $date > date( 'Y-m-d' ) ) {
                $appointmentsAfterToday[$date] = $appointments;
            } else {
                $appointmentsBeforeToday[$date] = $appointments;
            }
        }
        // Sort after today by date desc and before today by date asc
        krsort( $appointmentsBeforeToday );
        ksort( $appointmentsAfterToday );

        // remove today in past appointments
        if ( isset( $appointmentsBeforeToday[date( 'Y-m-d' )] ) ) {
            unset( $appointmentsBeforeToday[date( 'Y-m-d' )] );
        }

        return $this->render( 'admin/appointment/index.html.twig', [
            'appointments' => $this->appointmentService->getAppointments(),
            'appointmentsToday' => $appointmentsToday,
            'appointmentsAfterToday' => $appointmentsAfterToday,
            'appointmentsBeforeToday' => $appointmentsBeforeToday,
        ] );
    }

    #[Route( '/new', name: 'new', methods: ['GET', 'POST'] )]
    public function new( Request $request ) : Response
    {
        [$form, $response] = $this->createFormAppointment( $request );

        if ( $response ) {
            $this->addFlash( 'success', 'Votre rendez-vous a bien été enregistré.' );
            return $response;
        }

        return $this->render( 'admin/appointment/new.html.twig', [
            'form' => $form->createView(),
        ] );
    }

    private function createFormAppointment( Request $request, Appointment $appointment = new Appointment() ) : array
    {
        $form = $this->createForm( NewAppointmentForm::class, new AppointmentData( $appointment ) );

        $form->handleRequest( $request );
        if ( $form->isSubmitted() && $form->isValid() ) {
            $data = $form->getData();
            $this->appointmentService->addAppointment( $data );

            return [$form, $this->redirectToRoute( 'app_admin_appointment_index' )];
        }

        return [$form, null];
    }

    public function createUpdateFormAppointment( Request $request, Appointment $appointment = new Appointment() ) : array
    {
        $form = $this->createForm( NewAppointmentForm::class, new AppointmentData( $appointment ) );

        $form->handleRequest( $request );
        if ( $form->isSubmitted() && $form->isValid() ) {
            $data = $form->getData();
            $this->appointmentService->updateAppointmentWithDto( $data );

            return [$form, $this->redirectToRoute( 'app_admin_appointment_index' )];
        }

        return [$form, null];
    }

    #[Route( '/{id<\d+>}', name: 'show', methods: ['GET'] )]
    public function show( Appointment $appointment = null ) : Response
    {
        if ( !$appointment ) {
            $this->addFlash( 'danger', 'Rendez-vous introuvable.' );
            return $this->redirectToRoute( 'app_admin_appointment_index' );
        }

        return $this->render( 'admin/appointment/show.html.twig', [
            'appointment' => $appointment,
        ] );
    }

    #[Route( '/{id<\d+>}/edit', name: 'edit', methods: ['GET', 'POST'] )]
    public function edit( Request $request, Appointment $appointment = null ) : Response
    {
        if ( !$appointment ) {
            $this->addFlash( 'danger', 'Rendez-vous introuvable.' );
            return $this->redirectToRoute( 'app_admin_appointment_index' );
        }

        [$form, $response] = $this->createUpdateFormappointment( $request, $appointment );

        if ( $response ) {
            $this->addFlash( 'success', 'Votre rendez-vous a bien été modifié.' );
            return $response;
        }

        return $this->render( 'admin/appointment/update.html.twig', [
            'form' => $form->createView(),
        ] );
    }

    #[Route( '/{id<\d+>}/confirm', name: 'confirm', methods: ['GET', 'POST'] )]
    public function confirm( Request $request, Appointment $appointment = null ) : Response
    {
        if ( !$appointment ) {
            $this->addFlash( 'danger', 'Rendez-vous introuvable.' );
            return $this->redirectToRoute( 'app_admin_appointment_index' );
        }

        if ( $this->isCsrfTokenValid( 'confirm_appointment' . $appointment->getId(), $request->request->get( '_token' ) ) ) {
            $this->appointmentService->confirmAppointment( $appointment );

            $this->addFlash( 'success', 'Rendez-vous confirmé avec succès.' );
            return $this->redirectToRoute( 'app_admin_appointment_show', ['id' => $appointment->getId()] );
        }

        return $this->redirectToRoute( 'app_admin_appointment_index' );
    }

    #[Route( '/{id<\d+>}/cancel', name: 'cancel' )]
    public function cancel( Request $request, Appointment $appointment = null ) : Response
    {
        if ( !$appointment ) {
            $this->addFlash( 'danger', 'Rendez-vous introuvable.' );
            return $this->redirectToRoute( 'app_admin_appointment_index' );
        }

        if ( $this->isCsrfTokenValid( 'cancel_appointment' . $appointment->getId(), $request->request->get( '_token' ) ) ) {
            $this->appointmentService->cancelAppointment( $appointment );

            $this->addFlash( 'success', 'Rendez-vous annulé avec succès.' );
            return $this->redirectToRoute( 'app_admin_appointment_show', ['id' => $appointment->getId()] );
        }

        return $this->redirectToRoute( 'app_admin_appointment_index' );
    }

    #[Route( '/{id<\d+>}/delete', name: 'delete', methods: ['POST'] )]
    public function delete( Request $request, Appointment $appointment ) : Response
    {
        if ( $this->isCsrfTokenValid( 'delete' . $appointment->getId(), $request->request->get( '_token' ) ) ) {
            $this->appointmentService->deleteAppointment( $appointment );

            $this->addFlash( 'success', 'Rendez-vous supprimé avec succès.' );
        }

        return $this->redirectToRoute( 'app_admin_appointment_index', [], Response::HTTP_SEE_OTHER );
    }
}

templates/appointment/manage-update.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Gérer votre rendez-vous
{% endblock %}

{% block body %}
    <div class="max-w-5xl mx-auto">
        {{ form_start(form) }}
        <div class="space-y-12">

            <div class="border-b border-gray-900/10 pb-12">
                <h2 class="text-lg font-semibold leading-7 text-gray-900">Votre rendez-vous</h2>
                <p class="mt-1 text-sm leading-6 text-gray-600">Vous pouvez modifier les informations de votre
                    rendez-vous.
                </p>

                <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">
                    <div class="sm:col-span-4">
                        {{ form_row(form.date) }}
                    </div>

                    <div class="sm:col-span-3">
                        {{ form_row(form.time) }}
                    </div>
                </div>

                <div class="mt-10 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6">

                    <div class="col-span-full">
                        <label for="about" class="label">
                            Consignes
                        </label>
                        <div class="mt-2">
                            <textarea id="about" name="about" rows="3"
                                      class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6"></textarea>
                        </div>
                        <p class="mt-3 form-help">
                            Écrivez ici les consignes que vous souhaitez donner à votre coiffeuse.
                        </p>
                    </div>
                </div>
            </div>

            <div class="border-b border-gray-900/10 pb-12">
                <h2 class="text-lg font-semibold leading-7 text-gray-900">Vos informations</h2>
                <p class="mt-1 text-sm leading-6 text-gray-600">
                    Pensez à vous connecter pour modifier vos informations personnelles.
                </p>

                <dl class="divide-y divide-gray-100">
                    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                        <dt class="text-sm font-medium leading-6 text-gray-900">Nom</dt>
                        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ appointment.client.fullname }}</dd>
                    </div>
                    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                        <dt class="text-sm font-medium leading-6 text-gray-900">Contact</dt>
                        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ appointment.client.phone }}</dd>
                    </div>
                    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                        <dt class="text-sm font-medium leading-6 text-gray-900">Email</dt>
                        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ appointment.client.email }}</dd>
                    </div>
                    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                        <dt class="text-sm font-medium leading-6 text-gray-900">Prestation</dt>
                        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ appointment.prestation.name }}</dd>
                    </div>
                    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                        <dt class="text-sm font-medium leading-6 text-gray-900">Tarif</dt>
                        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
                            {{ appointment.amount }} €
                        </dd>
                    </div>
                </dl>
            </div>
        </div>

        <div class="mt-6 flex items-center justify-end gap-x-6">
            <a href="{{ path('app_appointment_manage', {token: appointment.token}) }}"
               class="btn-md btn-secondary">Annuler</a>
            <button type="submit"
                    class="btn-md btn-primary">
                Enregistrer
            </button>
        </div>
        {{ form_end(form) }}
    </div>


{% endblock %}

templates/appointment/manage-view-old.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Gérer votre rendez-vous
{% endblock %}

{% block body %}
    <div class="max-w-7xl mx-auto">
        <div class="px-4 sm:px-0">
            <h3 class="text-xl font-bold leading-7 text-gray-900">Votre rendez-vous</h3>
            <p class="mt-1 max-w-2xl text-sm leading-6 text-gray-500">
                Retrouvez toutes les informations concernant votre rendez-vous.
            </p>
        </div>
        <div class="mt-6 border-t border-gray-100">
            <dl class="divide-y divide-gray-100">
                <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Nom</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ appointment.client.fullname }}</dd>
                </div>
                <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Prestation</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ appointment.prestation.name }}</dd>
                </div>
                <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Date et heure</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">{{ appointment.date|date('d/m/Y') }}
                        à {{ appointment.time|date('H:i') }}
                    </dd>
                </div>
                <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                    <dt class="text-sm font-medium leading-6 text-gray-900">Tarif</dt>
                    <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
                        {{ appointment.amount }} €
                    </dd>
                </div>
                {% if appointment.statusConfirmed %}
                    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                        <dt class="text-sm font-medium leading-6 text-gray-900">A savoir</dt>
                        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
                            Voici quelques informations à savoir avant votre rendez-vous.
                            <ul class="list-disc pl-5">
                                <li>Les enfants sont interdits</li>
                                <li>1 seul accompagnant est autorisé</li>
                                <li>Le paiement se fait en espèce ou via le site, aucun autre moyen de paiement n'est
                                    accepté
                                </li>
                            </ul>
                        </dd>
                    </div>
                    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                        <dt class="text-sm font-medium leading-6 text-gray-900">Actions</dt>
                        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
                            <p class="text-sm text-gray-400 mb-5">
                                En payant maintenant, votre place sera réservée.
                            </p>
                            <ul class="flex gap-4 flex-col sm:flex-row">
                                {% if not appointment.paid %}
                                    <a href="{{ path('app_appointment_payment_start', {'id': appointment.id}) }}"
                                       class=" btn-md btn-primary">
                                        {{ icon('credit-card') }}
                                        <span>Payer</span>
                                    </a>
                                {% else %}
                                    <div class="border border-primary-500 text-primary-500 py-2 rounded-md h-11 px-5 text-base inline-flex items-center justify-center whitespace-nowrap shadow-sm space-x-2">
                                        {{ icon('check-circle') }}
                                        <span>Paiement effectué</span>
                                    </div>
                                {% endif %}
                                {% if appointment.date|date('Y-m-d') >= 'now'|date('Y-m-d') %}
                                    {% if appointment.time|date('H:i') >= 'now'|date('H:i') %}
                                        <a href="{{ path('app_appointment_manage_edit', {'token': appointment.token}) }}"
                                           class="btn-md btn-outline-primary">
                                            {{ icon('calendar-days') }}
                                            <span>Modifier</span>
                                        </a>
                                        <a href="" class="btn-md btn-secondary">
                                            {{ icon('calendar-x-2') }}
                                            <span>Annuler</span>
                                        </a>
                                    {% else %}
                                        <div class="border border-primary-500 text-primary-500 py-2 rounded-md h-11 px-5 text-base inline-flex items-center justify-center whitespace-nowrap shadow-sm space-x-2">
                                            Rendez-vous terminé
                                        </div>
                                    {% endif %}
                                {% endif %}
                            </ul>
                        </dd>
                    </div>
                    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                        <dt class="text-sm font-medium leading-6 text-gray-900">Facture</dt>
                        <dd class="mt-2 text-sm text-gray-900 sm:col-span-2 sm:mt-0">
                            <ul role="list" class="divide-y divide-gray-100 rounded-md border border-gray-200">
                                <li class="flex items-center justify-between py-4 pl-4 pr-5 text-sm leading-6">
                                    <div class="flex w-0 flex-1 items-center">
                                        <svg class="h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 20 20"
                                             fill="currentColor" aria-hidden="true">
                                            <path fill-rule="evenodd"
                                                  d="M15.621 4.379a3 3 0 00-4.242 0l-7 7a3 3 0 004.241 4.243h.001l.497-.5a.75.75 0 011.064 1.057l-.498.501-.002.002a4.5 4.5 0 01-6.364-6.364l7-7a4.5 4.5 0 016.368 6.36l-3.455 3.553A2.625 2.625 0 119.52 9.52l3.45-3.451a.75.75 0 111.061 1.06l-3.45 3.451a1.125 1.125 0 001.587 1.595l3.454-3.553a3 3 0 000-4.242z"
                                                  clip-rule="evenodd"></path>
                                        </svg>
                                        <div class="ml-4 flex min-w-0 flex-1 gap-2">
                                            <span class="truncate font-medium">resume_back_end_developer.pdf</span>
                                            <span class="flex-shrink-0 text-gray-400">2.4mb</span>
                                        </div>
                                    </div>
                                    <div class="ml-4 flex-shrink-0">
                                        <a href="#"
                                           class="font-medium text-indigo-600 hover:text-indigo-500">Download</a>
                                    </div>
                                </li>
                                <li class="flex items-center justify-between py-4 pl-4 pr-5 text-sm leading-6">
                                    <div class="flex w-0 flex-1 items-center">
                                        <svg class="h-5 w-5 flex-shrink-0 text-gray-400" viewBox="0 0 20 20"
                                             fill="currentColor" aria-hidden="true">
                                            <path fill-rule="evenodd"
                                                  d="M15.621 4.379a3 3 0 00-4.242 0l-7 7a3 3 0 004.241 4.243h.001l.497-.5a.75.75 0 011.064 1.057l-.498.501-.002.002a4.5 4.5 0 01-6.364-6.364l7-7a4.5 4.5 0 016.368 6.36l-3.455 3.553A2.625 2.625 0 119.52 9.52l3.45-3.451a.75.75 0 111.061 1.06l-3.45 3.451a1.125 1.125 0 001.587 1.595l3.454-3.553a3 3 0 000-4.242z"
                                                  clip-rule="evenodd"></path>
                                        </svg>
                                        <div class="ml-4 flex min-w-0 flex-1 gap-2">
                                            <span class="truncate font-medium">coverletter_back_end_developer.pdf</span>
                                            <span class="flex-shrink-0 text-gray-400">4.5mb</span>
                                        </div>
                                    </div>
                                    <div class="ml-4 flex-shrink-0">
                                        <a href="#"
                                           class="font-medium text-indigo-600 hover:text-indigo-500">Download</a>
                                    </div>
                                </li>
                            </ul>
                        </dd>
                    </div>
                {% endif %}
                {% if appointment.statusPending %}
                    {% if appointment.date|date('Y-m-d') > 'now'|date('Y-m-d') %}
                        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                            <dt class="text-sm font-medium leading-6 text-gray-900">Informations</dt>
                            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
                                <div class="alert alert-info">
                                    Votre rendez-vous est en attente de confirmation. Vous recevrez un email dès que
                                    votre
                                    rendez-vous sera confirmé.
                                </div>
                            </dd>
                        </div>
                    {% else %}
                        <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                            <dt class="text-sm font-medium leading-6 text-gray-900">Informations</dt>
                            <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
                                <div class="alert alert-warning">
                                    Votre rendez-vous n'a pas été confirmé. Il est donc annulé.
                                </div>
                            </dd>
                        </div>
                    {% endif %}

                {% endif %}
                {% if appointment.statusCanceled %}
                    <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
                        <dt class="text-sm font-medium leading-6 text-gray-900">Informations</dt>
                        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
                            <div class="alert alert-warning">
                                Ce rendez-vous a été annulé. Il n'est plus accessible malheureusement.
                            </div>
                        </dd>
                    </div>
                {% endif %}
            </dl>
        </div>
    </div>

{% endblock %}